event = [{"name": "id",
          "type": "varchar(256)"},
         {"name": "object",
          "type": "varchar(256)"},
         {"name": "api_version",
          "type": "varchar(256)"},
         {"name": "created",
          "type": "timestamp"},
         {"name": "data",
          "type": "varchar(max)"},
         {"name": "livemode",
          "type": "boolean"},
         {"name": "pending_webhooks",
          "type": "integer"},
         {"name": "request",
          "type": "varchar(256)"},
         {"name": "type",
          "type": "varchar(256)"}]
