file_upload = [{"name": "id",
                "type": "varchar(256)"},
               {"name": "object",
                "type": "varchar(256)"},
               {"name": "created",
                "type": "timestamp"},
               {"name": "filename",
                "type": "varchar(256)"},
               {"name": "purpose",
                "type": "varchar(256)"},
               {"name": "size",
                "type": "integer"},
               {"name": "type",
                "type": "varchar(256)"},
               {"name": "url",
                "type": "varchar(256)"}]
